### ISSUE TITLE
margin-top example in Stylelint

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#229]
Current Stylelint example is very small and is not so powerful. On my talk about Stylelint most of listeners remembered their pain in this example:

```css
.logo {
  margin-top: 10px;
  margin: 0 auto;
}
```

Second line overrides first one. I think everyone did this mistake and then spend a lot of times in debug.

Or maybe there is better example to show how Stylelint is powerful for everyone problems? @davidtheclark
